# Basic Information
title: Vu-Anh Le (Anh)
position: PhD Student | AI4Science
department: Department of Computer Science
university: University of Virginia
affiliation: Department of Computer Science, University of Virginia
affiliation_link: https://engineering.virginia.edu/departments/computer-science
university_link: https://www.virginia.edu/
email: mcu7uh (at) virginia [dot] edu

# Site settings for GitHub Pages
baseurl: ""
url: "https://vuanhle.github.io"

# Search Engine Optimization (SEO)
keywords: Vu-Anh Le, Le Vu Anh, AI4Science, closed-loop AI4Science, machine learning theory, constrained generative modelling, multiagent systems, bio-modelling, drug discovery, University of Virginia
description: Vu-Anh Le is a Computer Science Ph.D. student at the University of Virginia researching closed-loop, AI-driven scientific systems.
canonical: https://vuanhle.github.io/
author: Vu-Anh Le
lang: en-US

# Links
google_scholar: https://scholar.google.com/citations?hl=en&user=v3_DrtcAAAAJ
github_link: https://github.com/vuanhle
linkedin: https://www.linkedin.com/in/levuanh
cv_link: /assets/img/CV.pdf

# Images
avatar: /assets/img/avatar.webp
favicon: /assets/img/favicon.png
favicon_dark: /assets/img/favicon-dark.png

# Footnote
enable_footnote: false

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Sans Serif"

# Google Analytics ID
google_analytics:

remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
